#!/bin/bash
# Build Golang Application
echo go build main.go

# Login docker
echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

# push docker image
docker build . -t ssh-api \
&& docker push ssh-api