#!/bin/bash
# Login docker
echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

# Build Golang Application
echo go build -o dist/ssh-api \
&& docker build . -t ssh-api \
&& docker push ssh-api